#pragma once
#include <condition_variable>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <string>
#include <thread>
#include <vector>

#include <coroutine>

#include <lumen/core/event_loop.hpp>
#include "value.hpp"

namespace lumen_script {

// ─── Thread pool for the database calls ──────────────────────────────────────
//
// The three clients (SQLite, libpq, libmysqlclient) have a blocking API.
// Running them on the event loop thread would pin that whole core: every
// connection SO_REUSEPORT handed it would stop responding for as long as the
// query lasts.
//
// That is why a query suspends the handler —just like `await sleep`— and the
// real work happens here.  Each worker owns ONE connection, so there is no
// need to hand connections between threads or synchronize their use.
class DbPool {
public:
    ~DbPool();

    void start(size_t workers);

    // Free assignment: the first available worker takes it.
    void submit(std::function<void(size_t worker)> job);

    // Pinned to a specific worker.  A transaction needs this: BEGIN, the
    // queries and COMMIT have to go through the SAME connection, and each
    // worker owns one.
    void submit_to(size_t worker, std::function<void(size_t worker)> job);

    void stop();

    size_t size() const { return workers_.size(); }

private:
    std::vector<std::thread>                        threads_;
    std::vector<int>                                workers_;   // only for the size
    std::queue<std::function<void(size_t)>>              jobs_;
    std::vector<std::queue<std::function<void(size_t)>>> pinned_;
    std::mutex                                      mutex_;
    std::condition_variable                         cv_;
    bool                                            stopping_ = false;
};

// ─── Driver ──────────────────────────────────────────────────────────────────
//
// A driver is the minimum needed to talk to an engine: open a worker's
// connection, query and execute.  Everything is called from the pool, never
// from the event loop thread.
class DbDriver {
public:
    virtual ~DbDriver() = default;

    // Name it is imported and invoked with from Lumen Script: `sqlite`,
    // `postgres`, `mysql`.
    virtual const char* name() const = 0;

    // Configuration taken from the `<module>:` block of `app:`.
    virtual bool configure(const std::map<std::string, std::string>& options,
                           std::string& error) = 0;

    // Opens the connection of the given worker.  Called once per worker, the
    // first time work reaches it.
    virtual bool open(size_t worker, std::string& error) = 0;

    // SELECT: returns a List of Dict, one entry per row.
    virtual bool query(size_t worker, const std::string& sql,
                       const std::vector<Value>& args,
                       Value& out, std::string& error) = 0;

    // INSERT/UPDATE/DELETE/DDL: returns the number of affected rows.
    virtual bool exec(size_t worker, const std::string& sql,
                      const std::vector<Value>& args,
                      long long& affected, std::string& error) = 0;

    // Identifier generated by the last INSERT on that connection.  Not every
    // engine offers it reliably; the ones that do not say so.
    virtual bool last_insert_id(size_t worker, long long& id, std::string& error) {
        (void)worker; (void)id;
        error = std::string(name()) + ": last_id() is not available; use "
                "'insert ... returning id' with query()";
        return false;
    }

    size_t pool_size() const { return pool_size_; }
    void   set_pool_size(size_t n) { pool_size_ = n; }

protected:
    size_t pool_size_ = 4;
};

// ─── Module registry ─────────────────────────────────────────────────────────
//
// The compiled drivers register here.  Whether a module exists depends on the
// cmake options, so an `import` of one that is not compiled has to give a
// clear error and not a strange failure later on.
class DbRegistry {
public:
    static DbRegistry& instance();

    // Names of the drivers available in this binary.
    std::vector<std::string> available() const;
    bool                     has(const std::string& name) const;

    // Activates a module with its configuration and starts its pool.
    bool activate(const std::string& name,
                  const std::map<std::string, std::string>& options,
                  std::string& error);

    // Active driver, or nullptr if that module was not imported.
    DbDriver* active(const std::string& name) const;
    DbPool*   pool(const std::string& name) const;

    void shutdown();

private:
    DbRegistry();

    struct Slot {
        std::unique_ptr<DbDriver> driver;
        std::unique_ptr<DbPool>   pool;
        bool                      activated = false;
    };
    std::map<std::string, Slot> slots_;
};

// ─── Bridge with the engine coroutines ───────────────────────────────────────
//
// Suspends the handler, does the work in the pool and resumes it ON ITS OWN
// EVENT LOOP THREAD.  Resuming from the pool thread would touch loop
// structures from outside, which are not safe for that.
struct DbAwaitable {
    DbPool*                        pool;
    lumen::core::EventLoop*       loop;
    std::function<void(size_t)>    work;   // receives the worker: it picks the connection
    int                            pinned = -1;   // >= 0 inside a transaction

    bool await_ready() const noexcept { return false; }

    void await_suspend(std::coroutine_handle<> h) {
        // `this` lives until the co_await finishes, and the handle is resumed
        // exactly once, so capturing them by value is safe.
        auto* p = pool; auto* l = loop; auto w = work; int pin = pinned;
        auto job = [l, h, w](size_t worker) {
            w(worker);
            l->post([h]() mutable { h.resume(); });
        };
        if (pin >= 0) p->submit_to(static_cast<size_t>(pin), std::move(job));
        else          p->submit(std::move(job));
    }

    void await_resume() const noexcept {}
};

} // namespace lumen_script
