#pragma once
#include <condition_variable>
#include <cstdlib>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <set>
#include <string>
#include <thread>
#include <vector>

#include <coroutine>

#include <lux/core/event_loop.hpp>
#include <lux/task.hpp>
#include "value.hpp"

namespace lux_script {

// ─── Thread pool for the database calls ──────────────────────────────────────
//
// The three clients (SQLite, libpq, libmysqlclient) have a blocking API.
// Running them on the event loop thread would pin that whole core: every
// connection SO_REUSEPORT handed it would stop responding for as long as the
// query lasts.
//
// That is why a query suspends the handler —just like `await sleep`— and the
// real work happens here.  Each worker owns ONE connection, so there is no
// need to hand connections between threads or synchronize their use.
class DbPool {
public:
    ~DbPool();

    // in_transaction(worker): whether that worker's connection has a
    // transaction open, asked on the worker itself after every job.
    void start(size_t workers, std::function<bool(size_t)> in_transaction);

    // Free assignment: the first available worker takes it.
    void submit(std::function<void(size_t worker)> job);

    // Pinned to a specific worker.  A transaction needs this: BEGIN, the
    // queries and COMMIT have to go through the SAME connection, and each
    // worker owns one.
    void submit_to(size_t worker, std::function<void(size_t worker)> job);

    void stop();

    size_t size() const { return workers_.size(); }

private:
    std::vector<std::thread>                        threads_;
    std::vector<int>                                workers_;   // only for the size
    std::queue<std::function<void(size_t)>>              jobs_;
    std::vector<std::queue<std::function<void(size_t)>>> pinned_;
    std::vector<char>                               held_;   // connection inside a transaction
    std::mutex                                      mutex_;
    std::condition_variable                         cv_;
    bool                                            stopping_ = false;
};

// ─── Idle connection liveness, without a round trip ─────────────────────────
//
// Between statements an idle connection has nothing to read. A server that
// closed it (KILL, restart, idle timeout) leaves an EOF or a reset waiting in
// the kernel, visible to a non-blocking peek -- no packet sent. Pending bytes
// are ambiguous (a timeout notice before the close, or a TLS session ticket on
// a healthy connection), so they answer Unknown and the driver pings.
enum class SocketState { Alive, Dead, Unknown };
SocketState peek_socket(int fd);

// ─── Driver ──────────────────────────────────────────────────────────────────
//
// A driver is the minimum needed to talk to an engine: open a worker's
// connection, query and execute.  Everything is called from the pool, never
// from the event loop thread.
class DbDriver {
public:
    virtual ~DbDriver() = default;

    // Name it is imported and invoked with from Lux Script: `sqlite`,
    // `postgres`, `mysql`.
    virtual const char* name() const = 0;

    // Configuration taken from the `<module>:` block of `app:`.
    virtual bool configure(const std::map<std::string, std::string>& options,
                           std::string& error) = 0;

    // Opens the connection of the given worker.  Called once per worker, the
    // first time work reaches it.
    virtual bool open(size_t worker, std::string& error) = 0;

    // SELECT: returns a List of Dict, one entry per row.
    virtual bool query(size_t worker, const std::string& sql,
                       const std::vector<Value>& args,
                       Value& out, std::string& error) = 0;

    // INSERT/UPDATE/DELETE/DDL: returns the number of affected rows.
    virtual bool exec(size_t worker, const std::string& sql,
                      const std::vector<Value>& args,
                      long long& affected, std::string& error) = 0;

    // Whether the worker's connection is inside a transaction, asked of the
    // connection itself. The pool keeps such a worker for its own
    // transaction; see DbPool::start.
    virtual bool in_transaction(size_t worker) const = 0;

    // Identifier generated by the last INSERT on that connection.  Not every
    // engine offers it reliably; the ones that do not say so.
    virtual bool last_insert_id(size_t worker, long long& id, std::string& error) {
        (void)worker; (void)id;
        error = std::string(name()) + ": last_id() is not available; use "
                "'insert ... returning id' with query()";
        return false;
    }

    // A read outside a transaction, run on the CALLING thread (the event
    // loop) instead of the pool, for an engine where that can be cheaper
    // than the thread handoff. NotHandled sends it to the pool as usual --
    // the default, and the answer for anything that would block or run long.
    enum class Inline { NotHandled, Done, Failed };
    virtual Inline query_inline(const std::string& sql, const std::vector<Value>& args,
                                Value& out, std::string& error) {
        (void)sql; (void)args; (void)out; (void)error;
        return Inline::NotHandled;
    }

    size_t pool_size() const { return pool_size_; }
    void   set_pool_size(size_t n) { pool_size_ = n; }

protected:
    // The optional `pool N` key every driver accepts (1..64 workers).
    bool read_pool(const std::map<std::string, std::string>& options, std::string& error) {
        auto p = options.find("pool");
        if (p == options.end()) return true;
        long n = std::strtol(p->second.c_str(), nullptr, 10);
        if (n < 1 || n > 64) {
            error = std::string(name()) + ": 'pool' must be between 1 and 64";
            return false;
        }
        set_pool_size(static_cast<size_t>(n));
        return true;
    }

    size_t pool_size_ = 4;
};

// ─── Module registry ─────────────────────────────────────────────────────────
//
// The compiled drivers register here.  Whether a module exists depends on the
// cmake options, so an `import` of one that is not compiled has to give a
// clear error and not a strange failure later on.
class DbRegistry {
public:
    static DbRegistry& instance();

    // Names of the drivers available in this binary.
    std::vector<std::string> available() const;
    bool                     has(const std::string& name) const;

    // Activates a module with its configuration and starts its pool.
    bool activate(const std::string& name,
                  const std::map<std::string, std::string>& options,
                  std::string& error);

    // Active driver, or nullptr if that module was not imported.
    DbDriver* active(const std::string& name) const;
    DbPool*   pool(const std::string& name) const;

    void shutdown();

private:
    DbRegistry();

    struct Slot {
        std::unique_ptr<DbDriver> driver;
        std::unique_ptr<DbPool>   pool;
        bool                      activated = false;
    };
    std::map<std::string, Slot> slots_;
};

// A database call that failed comes back from await_db() as {"error": msg}
// -- never ambiguous, since a successful one is a List (query), an int
// (exec, last_id) or a bool (begin/commit/rollback), never a Dict. The
// drivers turn it into a raised error (catchable with try) right away.
inline bool db_failed(const Value& v, std::string& message) {
    if (!v.is_dict()) return false;
    auto it = v.as_dict().find("error");
    if (it == v.as_dict().end()) return false;
    message = it->second.to_string();
    return true;
}

// ─── Bridge with the engine coroutines ───────────────────────────────────────
//
// Suspends the handler, does the work in the pool and resumes it ON ITS OWN
// EVENT LOOP THREAD.  Resuming from the pool thread would touch loop
// structures from outside, which are not safe for that.
struct DbAwaitable {
    DbPool*                        pool;
    lux::core::EventLoop*       loop;
    std::function<void(size_t)>    work;   // receives the worker: it picks the connection
    int                            pinned = -1;   // >= 0 inside a transaction

    bool await_ready() const noexcept { return false; }

    void await_suspend(std::coroutine_handle<> h) {
        // `this` lives until the co_await finishes, and the handle is resumed
        // exactly once, so capturing them by value is safe.
        auto* p = pool; auto* l = loop; auto w = std::move(work); int pin = pinned;
        auto job = [l, h, w = std::move(w)](size_t worker) {
            w(worker);
            l->post([h]() mutable { h.resume(); });
        };
        if (pin >= 0) p->submit_to(static_cast<size_t>(pin), std::move(job));
        else          p->submit(std::move(job));
    }

    void await_resume() const noexcept {}
};

// ─── Bridge shared between bytecode and --native ─────────────────────────────
//
// --native phase 5.5: the logic of a database suspension used to live only
// inside run_db() (project.cpp), tied to VM::Result/NativeCtx. Extracted
// here, parameterized by DbOp instead of whichever native_id, so the code
// generated for a native route can invoke EXACTLY the same path bytecode
// already uses -- not an "almost the same" reimplementation (the same class
// of silent divergence that already caused two critical fixes in this
// phase). run_db() is now a thin adapter over this.
enum class DbOp { Query, Exec, LastId, Begin, Commit, Rollback };

// {"error": msg} -- how every engine failure reaches the .lux, as a normal value.
Value db_error(const std::string& msg);

// `pinned_workers`/`last_exec_workers`: the same map (module -> worker)
// NativeCtx already carries for a bytecode request today -- the caller
// (run_db(), or a route's generated native code) owns these maps and
// passes them by reference, alive for the whole duration of the request.
// `sql`/`params` are ignored for LastId/Begin/Commit/Rollback (they do not
// need them).
//
// `poisoned`: modules whose in-progress transaction has already seen a
// statement fail. A real SQL engine aborts the ENTIRE transaction the
// moment a statement inside it fails -- everything that comes after,
// including a final commit(), is rejected until a rollback() -- but the
// drivers at this layer (sqlite3/libpq/libmysqlclient) do not expose that
// state uniformly, and an engine error here is always a plain Value, never
// an exception (see the paragraph below): without this tracking, a `.lux`
// that does not check the result of EVERY exec()/query() (90% of the ones
// people write, GUIDE.md included: its own transactions example does not)
// keeps chaining statements over a connection whose first INSERT already
// failed, and the final commit() confirms all of them -- the ones that DID
// work AND the gap left by the one that did not. With this, any statement
// inside an already-marked transaction returns an immediate error without
// touching the driver, and commit() on it does a ROLLBACK instead and
// reports it as an error rather than a success. Lives in the same NativeCtx
// as pinned_workers/last_exec_workers, same lifetime.
//
// Never throws or raises an error beyond this function: an engine failure
// (module not configured, invalid SQL, driver failure) produces a
// Value::Dict {"error": message} as a normal result, exactly as before --
// the `.lux` (or the generated native code) decides what to do with it,
// the function never blows up the handler.
lux::Task<Value> await_db(DbOp op, const std::string& module, lux::core::EventLoop* loop,
                            const std::string& sql, std::vector<Value> params,
                            std::map<std::string, int>& pinned_workers,
                            std::map<std::string, int>& last_exec_workers,
                            std::set<std::string>& poisoned);

// Closes, with ROLLBACK, any transaction the handler left open (begin()
// with no commit() or rollback() by the time the route ends). Without
// this, the connection that opened it would stay pinned inside a
// transaction forever, and the next request to reuse it would inherit that
// half-finished state. Called once, right before building the response --
// see the call site in project.cpp (bytecode) and in the code that
// generates an async native route (native_gen.cpp). Empties
// `pinned_workers` when done.
lux::Task<void> rollback_pending_db(std::map<std::string, int>& pinned_workers,
                                         lux::core::EventLoop* loop);

} // namespace lux_script
